default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: Empleados_development

test:
  <<: *default
  database: Empleados_test

production:
  <<: *default
  database: Empleados_production
  username: Empleados
  password: <%= ENV["EMPLEADOS_DATABASE_PASSWORD"] %>
